matrix:
  include:
    - language: android
      dist: trusty
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          packages:
            - oracle-java8-installer
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - android-23
          - extra-android-m2repository
      script:
        - jdk_switcher use oraclejdk8
        - ./gradlew clean build assembleRelease
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      install: true
      before_install:
        - openssl aes-256-cbc -md md5 -d -k $SECRET_FILE -in release.jks.enc -out release.jks
      deploy:
        provider: releases
        api_key:
          secure: "RexfIIpI6kyvET5xDoTcll0Ce7jti63QcB1B3tVPtkkqbBpHzhb4n1eLapI/okIb6okn9Hsko5hy2hX5rqGIA3p5T/zUKTv7AwePblHmQr3LxOn8jnfPynIzJTxCd1hxuPLk/wLSwqSSoeBYAQuQNTP3oyQ5nE0LQ818V/k/PQ0j3aXCrkV6GdpgWqf16YAFIYpa2o8nQwVt3XlmLWq1OZtd3U3xH3nh8rK7atCcnV+WE52XBJyeUB9DMugJR0L+jq2A74kgA8DQ2RkKakBVGtfUdf7nXuzcCrtPck00ZdTCbgAe9Ah+KdPoLCHJerDuMOhky1H0KiMYIg00758TrrcDX9kmGugtA4o6wJjqPJPkr36fIRFPNiGhTCmFj1ZgImM77vwjh7cpdXxem6Y6suSQ5jKf6Y8zHA0skWBtszUffgPBwyeqBATXktzgy74NvtTdSxdFttm3xkSpTD36Zt5xLfqeyDqgW34gHUvX9USVG6pRizWgbTqG2KSRl//l9Qlw4Ab1KzRgN2/LEAlIPq3LQ4LZ45tOYDZbC+cHq9DeBOUr/yrGqt999ryfgQqr4jbUgw5341sVYqhtK0BmmmoX5ksDt5BuJlV9BRR8t6NDf6WIQv93yUHqLtdcN+usJ//PO3h1DJ+nYrwJ050X0M/xigw9ampU3ZtsWsI/FL4="
        file: android/build/outputs/apk/release/mptabs-${TRAVIS_BRANCH}-release.apk
        name: ${TRAVIS_BRANCH}
        draft: false
        prerelease: false
        skip_cleanup: true
        on:
          repo: drx-tn/mptabs
          branch: master
          tags: true
    - language: c++
      compiler: clang
      os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
      install:
        - brew install cppcheck qt
        - brew link --force qt
      before_script:
        - export QMAKESPEC=macx-clang
        - qmake -config release
      script:
        - make
        - macdeployqt qt/mptabs.app -verbose=3 -dmg
        - mv qt/mptabs.dmg qt/mptabs-${TRAVIS_BRANCH}.dmg
      deploy:
        provider: releases
        api_key:
          secure: "RexfIIpI6kyvET5xDoTcll0Ce7jti63QcB1B3tVPtkkqbBpHzhb4n1eLapI/okIb6okn9Hsko5hy2hX5rqGIA3p5T/zUKTv7AwePblHmQr3LxOn8jnfPynIzJTxCd1hxuPLk/wLSwqSSoeBYAQuQNTP3oyQ5nE0LQ818V/k/PQ0j3aXCrkV6GdpgWqf16YAFIYpa2o8nQwVt3XlmLWq1OZtd3U3xH3nh8rK7atCcnV+WE52XBJyeUB9DMugJR0L+jq2A74kgA8DQ2RkKakBVGtfUdf7nXuzcCrtPck00ZdTCbgAe9Ah+KdPoLCHJerDuMOhky1H0KiMYIg00758TrrcDX9kmGugtA4o6wJjqPJPkr36fIRFPNiGhTCmFj1ZgImM77vwjh7cpdXxem6Y6suSQ5jKf6Y8zHA0skWBtszUffgPBwyeqBATXktzgy74NvtTdSxdFttm3xkSpTD36Zt5xLfqeyDqgW34gHUvX9USVG6pRizWgbTqG2KSRl//l9Qlw4Ab1KzRgN2/LEAlIPq3LQ4LZ45tOYDZbC+cHq9DeBOUr/yrGqt999ryfgQqr4jbUgw5341sVYqhtK0BmmmoX5ksDt5BuJlV9BRR8t6NDf6WIQv93yUHqLtdcN+usJ//PO3h1DJ+nYrwJ050X0M/xigw9ampU3ZtsWsI/FL4="
        file: qt/mptabs-${TRAVIS_BRANCH}.dmg
        name: ${TRAVIS_BRANCH}
        draft: false
        prerelease: false
        skip_cleanup: true
        on:
          repo: drx-tn/mptabs
          tags: true
notifications:
  email: false
